name: Shell Run

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Wwelcome Bangaaru, Tishan and Udit
            run: |
                echo "Hi Tishan, Udit and Bangaaru "
                ls -ltra
                cat README.md
         
          - name: list All Files in Repo
            run: ls -ltar

          - name: Execution Shell script
            run:  sudo ./ascii-script.sh
                