name: My First Workflow

on: [push, fork]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Wwelcome Tishan and Udit
            run: echo "Hi Tishan Udit and Bangaaru"
          
          - name: List File
            run: ls

          - name: Read File
            run: cat README.md
