name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Wwelcome Tishan and Udit
            run: echo "Hi Tishan, Udit and Bangaaru "
          
          - name: List File
            run: ls

          - name: Read File
            run: cat README.md
